name: scroll_edge_listener
description: A widget triggers the attached listener based on the scroll position.
version: 0.1.0
homepage: https://github.com/jezsung/scroll_edge_listener.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
